[[redirects]]
from = "https://blair3sat.com/"
to = "https://www.blair3sat.org/"
status = 301
force = false
[[redirects]]
from = "https://www.blair3sat.com/"
to = "https://www.blair3sat.org/"
status = 301
force = false
[[redirects]]
from = "https://blair3sat-website.netlify.app/"
to = "https://www.blair3sat.org/"
status = 301
force = false
